### ISSUE TITLE
DeckBuilder for Crystal Clash

### ISSUE THREAD

**Issue by vlad9i22** [FrBrGeorge/PythonDevelopment2022#22]
- Задача: Создание сайта для составления коллод в полумёртвой игре "Crystal Clash".
- Репозиторий: https://github.com/vlad9i22/DeckBuilderDjangoWebsiteCC/
- Участники:
        1) Вартанов Дмитрий Александрович, 420, WrongWizzli
        2) Джулий Владимир Анатольевич, 319/2, vlad9i22

**Comment by FrBrGeorge** [comment]
Пока так:
- нет automation
- нет pydocstyle
- проект не запускается — не хватает критичного конфига
- после подкладывания конфига не запускается — просит какую-то БД

**Comment by FrBrGeorge** [comment]
Попытка  №2

- нет pydocstyle
- перевод неполный
- wheel содержит сборочные зависимости и гадит в site-packages

ХОР
