### ISSUE TITLE
Style Transfer App

### ISSUE THREAD

**Issue by pkorobov** [FrBrGeorge/PythonDevelopment2022#24]
Приложение для переноса стиля с одного изображения на другое

https://github.com/pkorobov/style_transfer_app

Участники:

- Коробов Павел Андреевич, 617 группа, @pkorobov
- Сомов Иван Сергеевич, 617 группа, @isomov

**Comment by FrBrGeorge** [comment]
Пока так:
- отсутствуют build зависимости
- отсутствует pydocstyle
- генерится пустая документация
­- отсутствует перевод

**Comment by pkorobov** [comment]
- Сделали сборку wheel
-  Поправили pydocstyle
- Документация больше не пустая

С помощью ```make project-demo``` можно запустить тесты, линтер, сборку документации и wheel
Установить wheel можно с помощью ```make install-wheel```

Запуск модуля:
python -m style_transfer_app --token 5205236575:AAGSCFg6t-H-GFI8LywovcV6d2yuq5xaUMg

И тогда можно будет протестить вот здесь:
https://t.me/MSU_style_transfer_bot

Один момент: есть проблемы с python3.10, лучше тестировать с 3.8-3.9

**Comment by FrBrGeorge** [comment]
ЗАЧЁТ
